### ISSUE TITLE
Can we support named endpoint ?

### ISSUE THREAD

**Issue by shcant** [prom3theu5/aspirational-manifests#102]
### 🚀 Feature Description
according to this [feature](https://learn.microsoft.com/en-us/dotnet/aspire/service-discovery/overview#named-endpoints) I'd like to expose different ports for named endpoints. Now aspirate tool ignore the configuration in manifest.

### ✔ Goals
- [x] Generate different port for every named endpoint

**Comment by prom3theu5** [comment]
Absolutely - I'll be back next week after holiday period and will implement this next on the list

**Comment by prom3theu5** [comment]
Implemented in `0.1.30-preview`
