### ISSUE TITLE
Non-interactive commands

### ISSUE THREAD

**Issue by adamtrip** [prom3theu5/aspirational-manifests#106]
Despite already having some non-interactive commands, I believe that in automatic deployments using something like Pipelines or GitHub Actions, lacks some options ( I think 😄).

It would be nice to have some args/params that we can pass to the `init`, `generate` & `apply`.

In the `init` command would be something like:
 ```aspirate init --registry private.registry.com --tag latest --template abc --user example --password Pa$$word```

`--registry`: custom registry
`--tag`: tag to apply
`--template`: template
`--user`: user of registry
`--password `: password of registry

In the `generate` command having something like:
`aspirate generate --projects all --secret Pa$$w0rd --generate-kustomize-manifest`

`--projects`: list of projects as `--projects apiservice,webfrontend,rediscache` or every project `--projects all`
`--secret`: secret 
`--generate-kustomize-manifest`: generate kustomize manifest

In the `apply` command having something like this:
`aspirate apply --secret Pa$$w0rd --cluster example`
`--secret`: secret
`--cluster`: cluster to be deployed to
I don't quite know how could you deploy to a k8s cluster via ssh or something like that, but having that would be cool as well.

**Comment by prom3theu5** [comment]
Hi Adam

Apply and Init already support non-interactive running like that
You can see in the docs [Apply](https://prom3theu5.github.io/aspirational-manifests/apply-manifests.html) and [Init](https://prom3theu5.github.io/aspirational-manifests/init-command.html)

Generate needs some work for project selection, and currently doesn't allow passing in the secret - so some work to do there.
However it does support setting some values - you can see them all [here](https://prom3theu5.github.io/aspirational-manifests/generate-command.html)

```
--user: user of registry
--password : password of registry
```

These are two items I don't really want to add to the init config - all commands use the systems docker / podman cli - so logging in with either docker or podman is enough there.

Once in kubernetes however - imagePullSecret would be needed.
I'd be open to adding them as options on the generate command, that way they could be stored as secrets

**Comment by prom3theu5** [comment]
Handles in 0.1.34-preview
Docs updated on generate command to show usage.

**Comment by adamtrip** [comment]
This is awesome David! I'll give it a try soon when I try to implement it into a CI/CD pipeline!

Thanks!
