### ISSUE TITLE
Helm Support

### ISSUE THREAD

**Issue by josephaw1022** [prom3theu5/aspirational-manifests#111]
### 🚀 Feature Description
As a developer, I'd like to be able to write <code> aspirate generate --output-format helm </code> and have a helm chart created.
After running that command, I'd like to be able to run <code>aspirate apply --helm</code>and have helm automatically update my chart for me. 

### ✔ Goals
- [ ] Have the generate command work with the helm tag
- [ ] Have the apply command work with the helm tag
- [ ] Look into making helm chart creation idempotent to where it will just update the templates and value files instead of creating another chart

### 🧰 Possible Solution
- Not too sure to be honest, would need to look more into the code base.

### 🚧 Blocked by
- Nothing to my knowledge

**Comment by prom3theu5** [comment]
Great idea
I'll get it started during the week. Got a few days break atm 😃

**Comment by SeidChr** [comment]
Hi,

I just came here to explicitly look for helm support with aspire/aspir8, because our client doesn't support to use k8s without helm.
 
I'd really love to see this become reality!
Is there any status?

**Comment by prom3theu5** [comment]
> I can contribute to this feature, @prom3theu5 if that's ok with you.

Sure thing ^^

**Comment by prom3theu5** [comment]
Implemented base support in v0.5.7-preview
