### ISSUE TITLE
Support multiple image tags in generate/build commands

### ISSUE THREAD

**Issue by DillonN** [prom3theu5/aspirational-manifests#116]
### 🚀 Feature Description
As a fan of the [docker-metadata action](https://github.com/docker/metadata-action), I'd like to be able to plug in the tag outputs to aspirate, in order to quickly push multiple tags at once. E.g. if I have a version 1.2.3, I can push tags `1.2.3`, `1.2`, and `latest` in one go.

### ✔ Goals
- [ ] Support passing multiple tags with `--container-image-tags` or maybe multiple `--container-image-tag` entries

### 🧰 Possible Solution
- `--container-image-tags` can match to the [`ContainerImageTags` MSBuild property](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0#containerimagetags)
  - Currently it's not possible to use this property even when defining it in the csproj file, as Aspirate will still put in `-p:ContainerImageTag="latest"`, which conflicts and causes a build error. The two versions are mutually exclusive.

### 🚧 Blocked by
- Nothing hopefully?

**Comment by prom3theu5** [comment]
Great idea - I'll implement Monday

**Comment by prom3theu5** [comment]
Sorry - I completely forgot about this - was on my todo list

Just been released in 0.6.15 - you can supply multiple tags to both build and generate
latest tag is always included, and is used in manifest generation though.
