### ISSUE TITLE
`--container-repository-prefix` doesn't respect `--non-interactive`

### ISSUE THREAD

**Issue by justinyoo** [prom3theu5/aspirational-manifests#117]
### 🔥 Bug Description

Related to #112 #115 with `v0.1.36-preview`.

I run the following `aspirate init` command:

```bash
# Case 1
aspirate init -cr <container-registry-url> -ct latest --container-repository-prefix "" --non-interactive

# Case 2
aspirate init -cr <container-registry-url> -ct latest --non-interactive
```

However, although it's set with the `--non-interactive` option, it still asks whether to skip the `container-repository-prefix` value or not. I expected to be automatically set to `null`, if the option is not passed.

![image](https://github.com/prom3theu5/aspirational-manifests/assets/1538528/f8432451-bbe3-4d2d-bb8f-347ddc1c5b33)

### 🧯 Possible Solution

* If the `--non-interactive` option is set, the `aspirate init` command should automatically skip setting the `container-repository-prefix` value and set it to `null`.

**Comment by justinyoo** [comment]
Aaaand, can I also ask its short-form argument, like `-crp` or `-rp` on top of `--container-repository-prefix`?

**Comment by prom3theu5** [comment]
I've removed prefix from being a required option, and added -crp as a shortname alias
Sorry it took so long 😄 
Version 0.1.39 has it - going out in a few

**Comment by justinyoo** [comment]
Thanks for your support! It would be a big win for me to prepare an Aspire workshop next week!

**Comment by prom3theu5** [comment]
you're welcome justin 😄
