### ISSUE TITLE
Support deploying the dashboard to kubernetes and docker compose

### ISSUE THREAD

**Issue by davidfowl** [prom3theu5/aspirational-manifests#118]
[We just merged the work](https://github.com/dotnet/aspire/pull/1774) to decouple the dashboard from the apphost so it can run as a separate process and as a [container image](https://github.com/dotnet/aspire/issues/1621). We should figure out how aspirate can deploy this image to the cluster and wire it up to make the end to end work.

A couple of high-level things:
- The dashboard isn't represented in the manifest today so it needs to be handled by aspirate separately
- The dashboard talks to [resource server](https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/Dashboard/proto/resource_service.proto) to make that list of resources work.
    - This resource server would need to be deployed as well and it would need to talk to the kubernetes API to get the aspire resources in order to make them show up in the dashboard.
    - The dashboard works without one and can act solely as an [otlp endpoint](https://github.com/dotnet/aspire/pull/1815)
- Services need to be configured to send telemetry to the dashboard
- The dashboard has no access control. It'll probably need to be an internal service only that can be manually port forwarded and launched in the browser (aspirate could have a command to automate this).

To enable pushing to more than one telemetry source, we might also want to consider using the otlp collector and configuring the dashboard as one of the places it pushes to. That would allow fanning out to multiple telemetry sinks (using the dashboard along side grafana etc).

For docker compose, there might be a simpler story for the resource server but I'm not 100% sure what it would look like as it would need to integrate with the local docker daemon.

**Comment by prom3theu5** [comment]
Awesome thanks David

It's great that you've made it available as a container image too. Massively simplifies things

I'll start drafting something together tonight. Is this for preview 3?

**Comment by davidfowl** [comment]
> I'll start drafting something together tonight. Is this for preview 3?

Yep! I think the deployment mechanics are more important than the resource server. At least we could tackle that part separately.

**Comment by davidfowl** [comment]
We're not re-branding to Aspire APM.

> Meanwhile what's the current workflow to use it as a standalore product, any "official" documentation about using it as a tool?

It's currently only shipping as a container image, not a dotnet tool.

**Comment by MithrilMan** [comment]
> > Meanwhile what's the current workflow to use it as a standalore product, any "official" documentation about using it as a tool?
> 
> It's currently only shipping as a container image, not a dotnet tool.

do you mean I can already use it in my docker compose? how?
I was looking for images in docker hub without luck, was looking for something like `mcr.microsoft.com/dotnet/aspire`

**Comment by davidfowl** [comment]
@prom3theu5 glad you're better now. I'd be happy to meet and whiteboard something (and contribute code).

> Can the preview 4 dashboard interoperate with services using Aspire Preview 3?

Yes!

**Comment by davidfowl** [comment]
Hey @prom3theu5 I'm back from Australia, so will setup time next week.

**Comment by prom3theu5** [comment]
Thanks @davidfowl 
Hope the flight was ok

**Comment by gmij** [comment]
thks @davidfowl 
I am currently working here, adding a Dashboard container in AppHost, and then adding my application to this container to establish an independent relationship between Dashboard and resource. However, it seems that currently, it is not very useful.

![image](https://github.com/prom3theu5/aspirational-manifests/assets/22893579/a95a2287-ee71-4e24-b783-806020fdd7b4)

**Comment by prom3theu5** [comment]
Added in v0.5.3-preview, which is building / releasing now
