### ISSUE TITLE
BuildAndPushContainerForProject fails silently when older versions of Docker are installed

### ISSUE THREAD

**Issue by AmmonRoberts** [prom3theu5/aspirational-manifests#121]
### 🔥 Bug Description
When running `aspirate generate`, the command will fail silently once it gets to the `BuildAndPushContainerForProject` step. This seems to be due to the `docker info --format json` command outputting the string "json" instead of normal Docker info in JSON format.

I installed Rancher Desktop but kept Docker Desktop installed. It turned out that I had an older version of Docker Desktop installed (I believe 4.10.x) and the version of the Docker engine that was installed was  20.10.23.

### 🔍 Steps to Reproduce the Bug
1. Install old version of Docker (make sure it's highest in your PATH if you have multiple versions)
2. Navigate to your AppHost directory
3. Run `aspirate init` if you haven't already
4. Run `aspirate generate`
5. See it silently fail after logging "Building all project resources, and pushing containers:"

### 🧯 Possible Solution
In the end, it's a Docker issue, but better logging would be extremely helpful here. I'm not fully sure what that would look like, but something at least logging the JsonException instead of failing silently would make a big difference in troubleshooting.

**Comment by prom3theu5** [comment]
Will investigate a better way to handle this, and introduce better logging around the process checks for availability of docker
