### ISSUE TITLE
Volumes are not generated in the docker compose file

### ISSUE THREAD

**Issue by Depechie** [prom3theu5/aspirational-manifests#123]
### 🔥 Bug Description
I have a project where I bind several volumes per docker container to load configuration files.
But generating the docker compose file does not include these volumes.

### 🔍 Steps to Reproduce the Bug
1. Clone https://github.com/Depechie/OpenTelemetryGrafana/tree/aspire/code/otel.AppHost
2. aspirate generate --output-format compose
3. Open the docker compose and see that there are no volumes defined

**Comment by prom3theu5** [comment]
Unfortunately we can't support volumes until Aspire outputs volume information in the manifest
Aspir8 operates solely on the information output in the manifest file that is produced from the AppHost.

You can see whats available by running this in the AppHost directory of the otel project

`dotnet run --publisher manifest --output-path manifest.json`

Right now, there aren't any volume resources, and without them aspir8 has no way to know that it can create them 😢

**Comment by Depechie** [comment]
Thanks for the clarification!

**Comment by davidfowl** [comment]
We've done work in preview 5 to preserve container volumes for container resources specifically.
