### ISSUE TITLE
`aspirate apply` doesn't respect the `--image-pull-policy Always` option from `aspirate generate`

### ISSUE THREAD

**Issue by justinyoo** [prom3theu5/aspirational-manifests#127]
### 🔥 Bug Description

In Azure Container Registry and Azure Kubernetes Service environment,

Even if I run the `aspirate generate` command with the `--image-pull-policy Always` option, the `aspirate apply` command doesn't force to pull the new image.

I'm not sure it's the issue from Aspirate or somewhere else, though.

### 🔍 Steps to Reproduce the Bug

1. Run the command `aspirate generate --image-pull-policy Always --non-interactive`
2. Run the command `aspirate apply -k '{{ AKS_CLUSTER_NAME }}' --non-interactive`
3. Check the console message saying "unchanged" like:

    ```bash
    configmap/apiapp-env unchanged
    configmap/cache-env unchanged
    configmap/webapp-env unchanged
    service/apiapp unchanged
    service/cache unchanged
    service/webapp unchanged
    deployment.apps/apiapp configured
    deployment.apps/cache configured
    deployment.apps/webapp configured
    ```

4. Check the web app on a web browser
5. Confirm the updated web app image has not been applied.

### 🧯 Possible Solution

I have to destroy all containers from AKS, remove all container images from ACR, then run `aspirate generate` and `aspirate apply` to get the updated one.

**Comment by prom3theu5** [comment]
You can now pass '-r' when running Apply
This will perform a rollout restart of the services after applying the manifests - hopefully this should work for you
Just gone out in v0.1.40 😄

**Comment by justinyoo** [comment]
Thanks @prom3theu5 I've got another session tonight and will see how it's going!
