### ISSUE TITLE
`aspirate generate -ct v1` or `aspirate build -ct v2` doesn't override the fallback tag from `aspirate init -ct latest`

### ISSUE THREAD

**Issue by justinyoo** [prom3theu5/aspirational-manifests#128]
### 🔥 Bug Description

Related to #127 

When I initialise the Aspire project with the command, `aspirate init -ct latest`, it generates `aspirate.json` and `latest` is set as the fallback tag.

However, if I run the command, `aspirate generate -ct v1` or `aspirate build -ct v2` doesn't take precedence over `latest`. The Kustomization files are still pointing to the fallback tag, `latest` in this example.

### 🔍 Steps to Reproduce the Bug

1. Run the init command, `aspirate init -ct latest ...`
2. Run the generate command, `aspirate generate -ct v1 ...` or build command, `aspirate build -ct v2 ...`
3. Check the `deployment.yml` files under the `aspirate-output/*` directory that point to the `latest` tag

**Comment by prom3theu5** [comment]
Thanks - just fixed, will be going out in the release which also fixes #127 in the next hour :)
