### ISSUE TITLE
Garbled code

### ISSUE THREAD

**Issue by Varorbc** [prom3theu5/aspirational-manifests#129]
### 🔥 Bug Description
Garbled code

### 🔍 Steps to Reproduce the Bug
![image](https://github.com/prom3theu5/aspirational-manifests/assets/5714438/c3c6236d-f8e9-4909-b63f-648f59bd95b3)

### 🧯 Possible Solution
* Usefull tips or places to start go here.

**Comment by prom3theu5** [comment]
Sorry going to have to close this
These messages are coming direct from the dotnet sdk, not aspir8.
