### ISSUE TITLE
Generate command with output format compose does not generate a docker-compose file

### ISSUE THREAD

**Issue by yannhodiesne** [prom3theu5/aspirational-manifests#137]
### 🔥 Bug Description
When using the command `aspirate generate --output-format compose` by following the documentation [here](https://prom3theu5.github.io/aspirational-manifests/generate-command.html), only the manifest.json file gets generated and the command exits with error code 1

Here is the full output:
```
$ aspirate generate --output-format compose

     _                    _           ___
    / \     ___   _ __   (_)  _ __   ( _ )
   / _ \   / __| | '_ \  | | | '__|  / _ \
  / ___ \  \__ \ | |_) | | | | |    | (_) |
 /_/   \_\ |___/ | .__/  |_| |_|     \___/
                 |_|
Handle deployments of a .NET Aspire AppHost


Generating Aspire Manifest for supplied App Host:


Executing: dotnet run --project "/Users/username/Projets/AspireSample/AspireSample.AppHost/." -- --publisher manifest --output-path manifest.json
Génération...
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.0.0-preview.4.24156.9+692dc41a65da572a7df25d53a9f2880afe59fdd8
info: Aspire.Hosting.Publishing.ManifestPublisher[0]
      Published manifest to: /Users/username/Projets/AspireSample/AspireSample.AppHost/manifest.json
(✔) Done:  Created Aspire Manifest At Path: /Users/username/Projets/AspireSample/AspireSample.AppHost/manifest.json

Applying values for all automatically generated secrets.

Successfully generated a value for database's Input Value 'password'
You will now be prompted to enter values for any secrets that are not generated automatically.

(✔) Done:  Input values have all been assigned.
```

### 🔍 Steps to Reproduce the Bug
1. Create a starter Aspire project
2. Run `aspirate generate --output-format compose` inside the AppHost
3. A `manifest.json` gets generated, but the `./aspirate-output` directory has not even been created

Ran into this bug on a Windows and a macOS machine, both using .NET 8

**Comment by vbouzon** [comment]
Hi, 

I've faced the same behavior, silent crash, and after few tests, I found that .AddDatabase(...) call in AppHost project was the source of the issue.

**Comment by prom3theu5** [comment]
This should be fixed by the changes for Aspire preview 5 in release 0.5.0-preview.
