### ISSUE TITLE
Don't suppress error output that occur during actions

### ISSUE THREAD

**Issue by danbopes** [prom3theu5/aspirational-manifests#139]
### 🔥 Bug Description
aspirate doesn't appear to be generating/pushing containers during the build step. It simply exits silently.

### 🔍 Steps to Reproduce the Bug
1. Create a new "Aspire .NET Starter Application" project using latest preview (.net 8). I added redis caching in the step where it asks.
2. Run `aspirate generate`.

Here's my output from the command `aspirate generate`:

```
     _                    _           ___
    / \     ___   _ __   (_)  _ __   ( _ )
   / _ \   / __| | '_ \  | | | '__|  / _ \
  / ___ \  \__ \ | |_) | | | | |    | (_) |
 /_/   \_\ |___/ | .__/  |_| |_|     \___/
                 |_|
Handle deployments of a .NET Aspire AppHost


Generating Aspire Manifest for supplied App Host:


Executing: dotnet run --project "C:\Users\Daniel\Documents\AspireTest\AspireTest.AppHost\." -- --publisher manifest --output-path manifest.json
Building...
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.0.0-preview.4.24156.9+692dc41a65da572a7df25d53a9f2880afe59fdd8
info: Aspire.Hosting.Publishing.ManifestPublisher[0]
      Published manifest to: C:\Users\Daniel\Documents\AspireTest\AspireTest.AppHost\manifest.json
(?) Done:  Created Aspire Manifest At Path: C:\Users\Daniel\Documents\AspireTest\AspireTest.AppHost\manifest.json

Applying values for all automatically generated secrets.
You will now be prompted to enter values for any secrets that are not generated automatically.

(?) Done:  Input values have all been assigned.
No Dapr components selected, skipping Dapr annotations.

Gathering container details for each project in selected components

(?) Done:  Populated container details cache for project apiservice
(?) Done:  Populated container details cache for project webfrontend

Gathering Tasks Completed - Cache Populated.

Building all project resources, and pushing containers:

```

I'm at a loss where to go from here. The CLI offers no debugging/verbosity support, and I don't know why the project resources aren't being built.

**Comment by danbopes** [comment]
After debugging some more, the issue appears to lie in the ValidateBuilderOutput function:
```
var builderInfo = JsonDocument.Parse(builderCheckResult.Output);
```

For some reason my docker image is just returning "json\n" as the output, and nothing else, so I'm going to dig into this deeper. However, for this issue, I'd still state this is a bug, and add that when errors occur that prematurely exit the program should be outputted to the screen, not just squelched/ignored.

**Comment by lglowinski** [comment]
@danbopes I had the same issue

Changing ```docker info --format json``` to ```docker info --format "{{json .}}"``` seems to fix this problem

**Comment by danbopes** [comment]
I was using an older version of docker. After updating it, it solved one of my issues. Please just don't squelch errors!

**Comment by prom3theu5** [comment]
I agree that the verbosity output is a bit meh
I added #62 a while back for someone to pick up if they wanted, as I tried to stay on top of upstream changes in Aspire.

For now i've just added logging of the exceptions that occur during action executor calls.
This will be out in 0.5.1-preview in a few mins ( #143 )
