### ISSUE TITLE
Error executing action 'SubstituteValuesAspireManifestAction': System.ArgumentException: Unknown dictionary in placeholder {db.inputs.password}.

### ISSUE THREAD

**Issue by compfaculty** [prom3theu5/aspirational-manifests#147]
### 🔥 Bug Description
 aspirate generate  fails with error:
 
Error executing action 'SubstituteValuesAspireManifestAction':
System.ArgumentException: Unknown dictionary in placeholder {db.inputs.password}.

### 🧯 Possible Solution
* Usefull tips or places to start go here.

**Comment by prom3theu5** [comment]
Any chance you could share the manifest.json file please that was generated in the AppHost directory?
Thanks

**Comment by compfaculty** [comment]
[manifest.json](https://github.com/prom3theu5/aspirational-manifests/files/14977847/manifest.json)

I believe the issue could be on my side , I haven't find to much info how I need to setup the secrets in my project to make everything right. 
So this is also my Program,cs  from AppHost:
`
var builder = DistributedApplication.CreateBuilder(args);

var pgpassword = builder.Configuration["PGPASSWORD"];
var postgresdb = builder
    .AddPostgresContainer(name: "db", port: 5432, password: pgpassword)
    .AddDatabase("postgres");

var rabbitmqp = builder.Configuration["RABBITMQ_PASSWORD"];
var rabbit = builder.AddRabbitMQContainer(
    name:"rabbit", port: 5672,  password: rabbitmqp);

var nmap = builder
    .AddProject<Projects.Gur8Aspire_NetworkExplorer>("nmap")
    .WithReference(rabbit);

var apiservice = builder
    .AddProject<Projects.Gur8Aspire_ApiService>("apiservice")
    .WithReference(postgresdb)
    .WithReference(nmap);

builder.AddProject<Projects.Gur8Aspire_Blazor>("webfrontend")
    .WithReference(apiservice);


var app = builder.Build();

app.Run();
`

And  part of appsettings.json from web API:

`

{
  "Aspire": {
    "Npgsql": {
      "EntityFrameworkCore": {
        "PostgreSQL": {
          "ConnectionString": "Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=;Include Error Detail=true",
          "DbContextPooling": true,
          "HealthChecks": true,
          "Tracing": true
        }
      }
    },
    "RabbitMQ": {
      "Client": {
        "HealthChecks": true,
        "ConnectionString": "amqp://user:password@localhost:5672"
      }
    }
  },
`

**Comment by prom3theu5** [comment]
Thanks for your manifest

It looks like Aspire preview 1-4, not preview 5 (latest) because they'e now moved inputs to be a top level parameters object not part of the container resource like your manifest shows

```json
 "inputs": {
        "password": {
          "type": "string",
          "secret": true,
          "default": {
            "generate": {
              "minLength": 10
            }
          }
        }
      }
    },
    
    ```
    
    In the latest preview of Aspire that Aspirate supports this should be a parameter.v0 resource, not part of the container. Unfortunately there were lots of breaking changes in preview5, but its not GA yet :)
