### ISSUE TITLE
[Feature] Allow using dockerfiles with compose

### ISSUE THREAD

**Issue by hades200082** [prom3theu5/aspirational-manifests#152]
### 🚀 Feature Description
As a devops admin, I'd like to be able to deploy my stack using heroku-like services such as dokku, caprover and coolify, in order to utilise my existing VPS infrastructure for hosting.

### ✔ Goals
- [ ] Add optional support for existing dockerfiles in projects when using compose format
- [ ] Add option to generate dockerfiles along with compose file

### 🧰 Possible Solution
I'll use Coolify as an example since it's the one I'm most familiar with.

In Coolify, I link a new "project" to my Github repo and give it a branch and the location within the repo of my docker-compose file.

Coolify loads the docker-compose file and, in the UI, it then gives me the ability to set environment variables that it has found in the docker-compose ( see #151 ).

I set the environment variables as needed, then click "deploy". Coolify then git-pulls the repo on the deployment server and runs the docker compose.

With the current Aspirate compose files this would fail since the deployment server knows nothing about .Net or Aspire and does not have the project images in its local docker registry.

By allowing the use of dockerfiles, the generated compose file can include a [build specification](https://docs.docker.com/compose/compose-file/build/) in the .Net project service definitions, rather than an image, that uses the dockerfile to build the image automatically on the deployment server.

### 🚧 Blocked by
- Maybe #151

**Comment by prom3theu5** [comment]
This has been handled in v0.6.6-preview
