### ISSUE TITLE
Supplying private Docker image repositories to push images to

### ISSUE THREAD

**Issue by dotnetian** [prom3theu5/aspirational-manifests#164]
I'm not sure whether this is a problem of mine or the tool, but when I try to supply a custom private image repository to push images to it on `aspirate generate`, it gives an error. But removing the image repo from the aspirate settings JSON file works fine and pushes the images to Docker Desktop.

Is there a way to provide repo credentials too?

**Comment by prom3theu5** [comment]
Do you have examples of what you are trying?
Are you setting the container-repository input flags from https://prom3theu5.github.io/aspirational-manifests/generate-command.html#cli-options-optional ?

Authentication must be done outside of aspirate using the docker or podman cli to login atm - I will look at expanding in the future if required in aspirate - but its not really its responsibility I dont think
