### ISSUE TITLE
aspirate generate should try to use existing secrets file (if exists), instead of prompting for input

### ISSUE THREAD

**Issue by danbopes** [prom3theu5/aspirational-manifests#165]
aspirate generate should attempt to read existing secrets instead of prompting for all the secrets, and then later on, trying to figure out how to handle the secrets file

**Comment by prom3theu5** [comment]
Hi

It does do this

When it detects that an existing secret file is in use, it asks you if you'd like to use existing, or replace a value.
If you use existing, it wont touch them, and will reuse what you previously set

**Comment by danbopes** [comment]
@prom3theu5 It does it at the end: After the input phase of having to reenter all the values.

**Comment by prom3theu5** [comment]
It only does that to secrets that are marked as manual input as opposed to generated secrets in the aspire manifest. 

This will be changing over the next few weeks though, and the experience will be unified across secret types (manual and generated). State management is changing with some changes I'm making this week (not secret state, aspirate state itself run on run, so a new run will recognise a previous run against same project name and same filesystem path

**Comment by prom3theu5** [comment]
Secrets have been redesigned entirely now
Their state is combined with the aspirate-state.json file.

You wont be prompted for them now unless they are marked as manual input in the aspire manifest, and not generated.
