### ISSUE TITLE
Error: Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by TheLever** [prom3theu5/aspirational-manifests#170]
### 🔥 Bug Description
aspire 8.0.0-preview.6.24214.1/8.0.100
aspirate 1.0.1+c34c0d596af202e66e63098e803a3b88104660ed

Running aspirate generate fails with "Error: Value cannot be null. (Parameter 'key')"

### 🔍 Steps to Reproduce the Bug
1. Create aspire starter project - plain vanilla
2. Install aspirate using "dotnet tool install --global aspirate"
3. Run aspirate init in the AppHost folder, giving a local registry, all else to default values
4. Run aspirate generate
5. See error:

```
aspirate generate

 Successfully loaded existing aspirate bootstrap settings from 'C:\D\Dev\portal\portal.AppHost'.

Generating Aspire Manifest for supplied App Host:


Executing: dotnet run --project "C:\D\Dev\portal\portal.AppHost\." -- --publisher manifest --output-path manifest.json
Building...
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.0.0-preview.6.24214.1+6596fdc41a8d419876a6bf4abc17b7c66b9ef63a
info: Aspire.Hosting.Publishing.ManifestPublisher[0]
      Published manifest to: C:\D\Dev\portal\portal.AppHost\manifest.json
        (?) Done:  Created Aspire Manifest At Path: C:\D\Dev\portal\portal.AppHost\manifest.json
Error: Value cannot be null. (Parameter 'key')
```
### 🧯 Possible Solution
* It is not clear to me how to get additional information to help diagnose

**Comment by prom3theu5** [comment]
Can you share the manifest thats been created please

**Comment by TheLever** [comment]
Thanks for the swift response. It turns out my "plain vanilla" aspire starter was not as plain and vanilla as I thought. When I did an actual fresh aspire starter app, aspirate generate worked. So, assuming the manifest generated by aspire is ok, where should I search?

There was no manifest generated (in the failing case) from aspirate, I only have the manifest generated by aspire. Is that of interest?

**Comment by prom3theu5** [comment]
Yw - Ahh ok so its working now?
If not - Run what aspir8 runs to generate the manifest and share that please in your AppHost directory:=

`dotnet run --project . -- --publisher manifest --output-path manifest.json`

That should generate a manifest.json file, it seems for some reason - Aspir8 was unable to load the generated file, which is where the error `Error: Value cannot be null (Parameter 'key')` is coming from

**Comment by TheLever** [comment]
It is working on the plan, vanilla starter solution, not on the solution, I thought was "close enough" to plain vanilla. Do you want to see the manifest generated by the ```dotnet run --project . -- --publisher manifest --output-path manifest.json```?

**Comment by prom3theu5** [comment]
Yeah please :)

**Comment by prom3theu5** [comment]
Actually - I just noticed, you have a really old version of aspirate installed
1.0.1 is actually one of the first releases, when it wasn't marked as prerelease - I thought I unlisted that my bad

```bash
aspirate --version

     _                    _           ___
    / \     ___   _ __   (_)  _ __   ( _ )
   / _ \   / __| | '_ \  | | | '__|  / _ \
  / ___ \  \__ \ | |_) | | | | |    | (_) |
 /_/   \_\ |___/ | .__/  |_| |_|     \___/
                 |_|
Handle deployments of a .NET Aspire AppHost

0.6.8-preview+f9e8af3d524473295c8f5da6d68c27af70c3739e
```

**Comment by prom3theu5** [comment]
Ensure you install with the prerelease flag.
I will make sure 1.0.1 gets unlisted

```bash
dotnet tool install -g aspirate --prerelease
Tool 'aspirate' was successfully updated from version '0.6.7-preview' to version '0.6.8-preview'.
```

**Comment by TheLever** [comment]
Wow! That was it! That worked. Now it fails in generating a Helm chart, but probably a different issue.

Thanks for your help :)

**Comment by prom3theu5** [comment]
Yw :)
