### ISSUE TITLE
Update Documentation with New Helm Output option 

### ISSUE THREAD

**Issue by josephaw1022** [prom3theu5/aspirational-manifests#185]
### 🚀 Feature Description
As a developer, I'd like to be able to see helm as an output format, in order to know how to utilize the helm generation feature.

### ✔ Goals
- [ ] Add Helm argument to the output format argument list in the generate page

**Comment by prom3theu5** [comment]
I did with the code changes - just forgot to publish the updated docs I think - will publish now

**Comment by prom3theu5** [comment]
Yeah that was it - doh! 😄 
https://prom3theu5.github.io/aspirational-manifests/generate-command.html#helm-chart
