### ISSUE TITLE
Aspirate generates secretGenerator entries ponting to non-existent files when --disable-secrets is set

### ISSUE THREAD

**Issue by AieatAssam** [prom3theu5/aspirational-manifests#186]
### 🔥 Bug Description
In **0.6.10-preview** and below (based on timeline of updates), when using --disable-secrets, aspirate would not create kustomize files with secretGenerator section even if aspire manifest includes secrets (at least generated ones). With **0.7.0-preview**, even though --disable-secrets is set (entire generation happens in CI with pipeline variables used via kustomize for secrets and is fully transient), the resultant output now includes secretGenerator pointing to .<name>.secrets env file that does not exist, resulting in the following error:

```
error: accumulating resources: accumulation err='accumulating resources from 'aidatahandler': 'C:\<SNIP>.AppHost\aspirate-output\<SNIP>' must resolve to a file': recursed accumulation of path 'C:\<SNIP>.AppHost\aspirate-output\<SNIP>': loading KV pairs: env source files: [.<SNIP>.secrets]: evalsymlink failure on 'C:\<SNIP>.AppHost\aspirate-output\<SNIP>\.<SNIP>.secrets' : CreateFile C:\<SNIP>.AppHost\aspirate-output\<SNIP>\.<SNIP>.secrets: The system cannot find the file specified.
```

Seems that secretGeneration section authoring only checks for presence of secrets, but does not verify if these are disabled
### 🔍 Steps to Reproduce the Bug
1. Create a new Aspire project
2. Add RabbitMQ messaging container and reference it in main project:
```csharp
var messaging = builder.AddRabbitMQ("messaging", port: 32860)
    .WithManagementPlugin()
    .PublishAsContainer();

builder.AddProject<Projects.<MAIN PROJECT>>("<MAIN PROJECT>")
    .WithReference(messaging)
```
3. Run aspirate generate interactively once with --disable-secrets --output-format kustomize, subsequently can be run with non-interactive
My own full commandline is:
`aspirate generate --non-interactive --image-pull-policy Always --disable-secrets --include-dashboard false --output-format kustomize`
5. Execute
`kubectl kustomize` in aspirate-output directory to produce the error

### 🧯 Possible Solution
I did not dig deep enough through the code to fully understand all the repercussions, but might be possible to augment hasSecrets parameter with disable secrets option value? Since currently we do not emit env file with secrets but are checking for it in secretGenerator.

**Comment by prom3theu5** [comment]
Thanks for reporting - sorted in 0.7.2-preview, buolding and pushing now - it'll be on nuget in 10 mins

**Comment by AieatAssam** [comment]
I can confirm that the secretGenerator section is no longer emitted. Thank you for rapid turnaround. Guess I can remove my python script in pipeline that did the yaml cleanup now :)

**Comment by prom3theu5** [comment]
Haha - you're welcome
Thanks for confirming 😄
