### ISSUE TITLE
[Feature] Using launch profiles with aspirate generate

### ISSUE THREAD

**Issue by christiannagel** [prom3theu5/aspirational-manifests#189]
### 🚀 Feature Description
As a developer, I'd like to select a launch profile, in order to use a specific app model definition with the .NET Aspire AppHost.

With the AppHost profile, multiple launch profiles are defined, e.g. *Azure* and *OnPremises*. Depending on the launch profile, different resources are defined in the app model. The AddProject method of the app-model allows to specify a launch profile name.

### ✔ Goals
- [ ] Don't just start the default launch profile, let a launch profile select to generate the `aspirate generate` output

### 🧰 Possible Solution
- Add an option --launch-profile with aspirate generate

### Workaround

I can create an Aspire manifest first, and use this manifest with `aspirate generate`

`dotnet run --launch-profile OnPremises -- --publisher manifest --output-path onpremises-manifest.json`

aspirate 0.7.3-preview

**Comment by prom3theu5** [comment]
Absolutely!  I'm away till Tuesday on AV. I'll implement the day I'm back

**Comment by prom3theu5** [comment]
Just released this in v0.7.4-preview: https://github.com/prom3theu5/aspirational-manifests/releases/tag/v0.7.4-preview

**Comment by christiannagel** [comment]
@prom3theu5 this was really fast, and - also in your location - Tuesday didn't start yet! Thank you!

**Comment by prom3theu5** [comment]
Yw. Aye not been back long but wanted a clear todo list going into tomorrow. First day back from a break is always some sort of fire-fighting 😃
