### ISSUE TITLE
aspirate generate does not use output-path with compose format

### ISSUE THREAD

**Issue by christiannagel** [prom3theu5/aspirational-manifests#190]
### 🔥 Bug Description
Changing the output format to `compose`, and passing a value to --output-path, the output is always written to `aspirate-output`

### 🔍 Steps to Reproduce the Bug
Use
`aspirate generate --aspire-manifest myaspiremanifest.json --output-format compose --output-path ./one`

I've selected *one* and *./one* with the output, the output is always written to `aspirate-output`.

When not using the `--output-format` option, the new directory is selected.

aspirate 0.7.3-preview

**Comment by prom3theu5** [comment]
Thanks for reporting. I'm away till Tuesday on AV. Will fix then

**Comment by prom3theu5** [comment]
Fixed in #192
Will be adding launch profile support next, and releasing both as 0.7.4-preview later tonight
