### ISSUE TITLE
Configure source for docker images

### ISSUE THREAD

**Issue by vlachdev** [prom3theu5/aspirational-manifests#191]
### 🚀 Feature Description
Docker image should have configured source. Than when we deploy image to **ghcr.io** (Github) registry, image is automatically link to correct repository.

> If there is another way except manually mapping after image push, i would be glad for some direction

[Github docs - Labelling container images](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images)
[Github docs - Connecting a repository to a package](https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package)

### ✔ Goals
- [ ] Configure image owner from `.csproj`

### 🧰 Possible Solution

via CLI
```PS
docker build  --label "org.opencontainers.image.source=https://github.com/octocat/my-repo" 
```
dockerfile
```dockerfile
LABEL org.opencontainers.image.source=https://github.com/octocat/my-repo
```

As a source it can be fetched from `.csproj`. This way it is used via nuget packages i think
```xml
 <PropertyGroup>
   ...
    <RepositoryUrl>https://github.com/octocat/my-repo</RepositoryUrl>
   ...
 </PropertyGroup>
```

**Comment by prom3theu5** [comment]
This is already implemented. 
https://github.com/dotnet/sdk/blob/190723c80d85721cdc58fd906e645c4029b947bb/src/Containers/Microsoft.NET.Build.Containers/KnownStrings.cs#L13

See here in the .net 8 SDK source code, "ContainerRegistry" is deprecated in favor of ContainerRepository which aspir8 already supports.

You can either include ContainerRepository within your csproj, which is the recommended way, or you can specify on the command line with https://github.com/prom3theu5/aspirational-manifests/blob/main/src/Aspirate.Commands/Options/ContainerRepositoryPrefixOption.cs

**Comment by prom3theu5** [comment]
In fact you also have

CurrentState.ContainerRegistry, which is set by https://github.com/prom3theu5/aspirational-manifests/blob/main/src/Aspirate.Commands/Options/ContainerRegistryOption.cs

The produced image by the builder will be 

<container registry> / <container repo prefix> / image : tag

**Comment by vlachdev** [comment]
I don't know if i understand that correctly but i think we are taking about different thinks.
You are talking about image name, I'm talking about image annotation of source.

But non the less **thanks to you** i have found this: [sdk-container-builds docs](https://github.com/dotnet/sdk-container-builds/blob/main/docs/ContainerCustomization.md#default-container-labels)
Configuring `PrivateRepositoryUrl` in `.csproj` will add annotation for image: `org.opencontainers.image.source`

```xml
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PrivateRepositoryUrl>https://github.com/octocat/my-repo</PrivateRepositoryUrl>
```
> note: `PrivateRepositoryUrl`  is only written if `PublishRepositoryUrl` is `true`. Also relies on Sourcelink infrastructure being part of the build.

Alternative is to set annotation straight up:
```xml
  <ItemGroup>
    <ContainerLabel Include="org.opencontainers.image.source" Value="https://github.com/octocat/my-repo" />
  </ItemGroup>
```
