### ISSUE TITLE
Setting Deployment.yaml annotations

### ISSUE THREAD

**Issue by vlachdev** [prom3theu5/aspirational-manifests#196]
How to set up annotations for deployment manifest. I have tried configuring `IResourceBuilder.WithAnnotation()` in my `AppHost` but that does not seems to work.

Base on this template it should be possible to configure it:
https://github.com/prom3theu5/aspirational-manifests/blob/4ea316499c352bf588532b16020f363c2dc4ff3e/src/Aspirate.Cli/Templates/deployment.hbs#L2-L13

**Comment by prom3theu5** [comment]
It all depends on whats been output to the aspire manifest when its built by aspirate.
If aspire doesn't emit the annotations to the manifest then aspirate wont know about them

Do they appear in manifest.json?

**Comment by vlachdev** [comment]
Nope, they don't appear in the `manifest.json`, that does look like to be the issue.

Any chance you would know if `IResourceBuilder<T>.WithAnnotation Method` is the correct way to propagate annotation to manifest.json and then to deployment.yaml via **Aspirate**?

[link to docs](https://learn.microsoft.com/en-us/dotnet/api/aspire.hosting.applicationmodel.iresourcebuilder-1.withannotation?view=dotnet-aspire-8.0#aspire-hosting-applicationmodel-iresourcebuilder-1-withannotation-1(aspire-hosting-applicationmodel-resourceannotationmutationbehavior))

**Comment by prom3theu5** [comment]
I don't know a way unfortunately
You're likely going to have to use a patch strategy in kustomize to add them afterwards

The problem in they dont appear in the aspire manifest schema at all: https://[json.schemastore.org/aspire-8.0.json](https://json.schemastore.org/aspire-8.0.json)

**Comment by vlachdev** [comment]
oh that's bummer, thanks anyway at least it make sense now 😄

**Comment by prom3theu5** [comment]
Yw - I'll ping you back here if it ever gets added (will be post GA now for sure if it does - hopefully for 8.1) 😄

**Comment by jaimewukb** [comment]
Hey, i was wondering the same thing. Are we able to manually add to the manifest.json and then generate the deployment.yamls with the annotations?

**Comment by jaimewukb** [comment]
> Hey, i was wondering the same thing. Are we able to manually add to the manifest.json and then generate the deployment.yamls with the annotations?

For anyone wondering, I was able to do this by adding annotations object under each resource in the manifest file after it was generated.

```json
"annotations": {
        ...
      },
```

Then we can call `aspirate generate -m ./manifest.json` using the modified manifest file to generate deployments with the correct annotations. 

Would be good if we have support for this
