### ISSUE TITLE
Error: Could not find a part of the path for Postgres

### ISSUE THREAD

**Issue by dotnetian** [prom3theu5/aspirational-manifests#199]
### 🔥 Bug Description
When I try to do `aspirate apply`, I get this error:

```
(?) Done: Successfully set the Active Kubernetes Context to 'docker-desktop'
(!) Failed to apply manifests to cluster.
(!) Error: Could not find a part of the path
'...\Bargeh\Source\Build\Bargeh.Aspire.AppHost\aspirate-output\postgres\.postgres.secrets'.
```

### 🔍 Steps to Reproduce the Bug
1. run `aspirate init`
2. run `aspirate generate` with default options, or use helm (it doesn't matter)
3. run `aspirate apply` to docker-desktop or a real cluster

**Comment by prom3theu5** [comment]
Hi - What version of Aspir8 are you using?

Helm isn't used by the apply sub-command , only kustomize output type is. Helm and Compose are both classed as "ejected" manifest options, to manage outside of Aspir8

Did you have secrets enabled, then you have disabled them?

Whats the contents of your aspirate-state.json file (Don't worry - secrets are protected - you can mask if worried)

**Comment by prom3theu5** [comment]
Please test with Aspir8 version 0.7.6-preview which will be released in 10 mins
