### ISSUE TITLE
Convert Deployments to Stateful Sets 

### ISSUE THREAD

**Issue by josephaw1022** [prom3theu5/aspirational-manifests#216]
### 🚀 Feature Description
If you run aspirate generate and create the Kubernetes resources for your db, queue, or whatever you use, then the resource for the Kubernetes resource made is a deployment whether it's just plain manifests or helm. And while this works well for local development (for the most part), I think just going ahead and making them stateful sets would make it more convenient, so that it's closer to what a dev environment would look like and all I would have to do is configure the volumes/volume mounts and the actual pv/pvc for the dev environment.

### ✔ Goals
- [ ] Have Aspirate produce current aspire components that are stateful as stateful sets instead of deployments.
- [ ] Potentially have an option to have a pv and pvc made for your stateful set so manual tinkering with the pv/pvc is not needed

### 🧰 Possible Solution
- simply alter the code that produces the deployment for the dbs, queues, cache, etc... to stateful sets
- for the second goal, I would use the current cluster's default storage class for the pv

**Comment by prom3theu5** [comment]
Hi There

Currently stateful sets are created already if your manifest resource in aspire has a volume defined.
Deployments are stateless, and anything with a volume mount automatically become stateful sets during processing

Add a volume to cache, db etc in the AppHost, and you'll get stateful sets 😄

**Comment by josephaw1022** [comment]
You're the man
