### ISSUE TITLE
Emoji not shown on Windows powershell

### ISSUE THREAD

**Issue by timheuer** [prom3theu5/aspirational-manifests#22]
I noticed a diff in my output from your video...no emoji recognized.

![image](https://github.com/prom3theu5/aspirational-manifests/assets/4821/204b94cd-1dd9-409a-9718-6ae9e8dc640c)

**Comment by prom3theu5** [comment]
Cheers, Will investigate in parallels in the morning. It's probably macOS using post Unicode 13.0 emoji symbols that aren't compatible with windows. 

I will switch them out for something from here: https://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt tomorrow

**Comment by timheuer** [comment]
Discovered this is a thing with Powershell -- powershell does not do this by default, without adding this command:

```
[console]::InputEncoding = [console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
```

which after that results in:
![image](https://github.com/prom3theu5/aspirational-manifests/assets/4821/b2b4899e-364a-4c11-84c9-d5e1538ef436)

Regardless since using Spectre may want to use the emoji markup instead of pasting (e.g.,` :check_mark:` and `:rocket:`)

**Comment by prom3theu5** [comment]
Thats what I've done
Added a statement to the readme as well take from Spectre docs - we shouldn't really  mess with a users console encoding directly from the app, so leaving it open to the user to set that on their system ^^

Maybe the config file can enable / disable emoji support too.
