### ISSUE TITLE
"latest" tag always included during build

### ISSUE THREAD

**Issue by patrickklaeren** [prom3theu5/aspirational-manifests#225]
### 🔥 Bug Description
I am trying to do `aspirate build -ct 0.1.23` but this results in Aspirate running `-p:ContainerImageTags="\"latest;0.1.23\""`.

I want to not have `latest` included here.

Is this by design? Is there any way to ignore it?

### 🔍 Steps to Reproduce the Bug
1. Run `aspirate build -ct 0.1.23`
2. Latest tag is included

### 🧯 Possible Solution
Unknown. Could be by design?

**Comment by prom3theu5** [comment]
Aye its by design - I guess I can remove it if ct has been set?

**Comment by patrickklaeren** [comment]
If possible.

My use case is trying to push an image for another channel where I don't necessarily want the image to be known as `latest`.

I appreciate this may not be how it's intended, if that is the case, I'm happy to accept the functionality as is.

Though I suspect the semantics of passing in `ct`, would mean overriding any tags that would otherwise be fallen back on, including `latest`.

**Comment by prom3theu5** [comment]
No problem 😃 
It's a valid use case

Thanks for the sponsorship too!

**Comment by prom3theu5** [comment]
This is handled in v8.0.6 - releasing now, will be on nuget in around 10 mins
