### ISSUE TITLE
I forgot my password and when I want to recreate it, it asks for all kinds of password.

### ISSUE THREAD

**Issue by EkiciFurkan** [prom3theu5/aspirational-manifests#242]
### 🔥 Bug Description
when i go "aspirate generate" 

![image](https://github.com/user-attachments/assets/2c072e5d-f06b-4e7d-aadf-43ed428da8d2)

i got this screen and i don't know my password. Someone can help ?

**Comment by chrisgodfrey** [comment]
Manually delete the aspirate-state.json, re-run 'aspirate build', and say 'n' when it asks you to re-use settings, it should then prompt you to set a new password.

**Comment by EkiciFurkan** [comment]
> Manually delete the aspirate-state.json file, re-run 'aspirate generate', and say 'n' when it asks you to re-use settings, it should then prompt you to set a new password.

Thank you <3
