### ISSUE TITLE
Any prompt input should be allowable args in the CLI

### ISSUE THREAD

**Issue by timheuer** [prom3theu5/aspirational-manifests#37]
### 🚀 Feature Description
As a CI/CD author, I'd like to be able to automate `init` and other commands that accept prompt input, in order to automate this from non-interactive scenarios (CI/CD).

### ✔ Goals
- [x] Change `init` prompts to read CLI input args if present (e.g. `aspirate init --container-registry foobar:5000`)
- [x] Provide a non-interactive bypass in CLI to not block any automation if args not present (e.g., `aspirate init --non-interactive` or something)

**Comment by prom3theu5** [comment]
I like the sound of that
It could be rolled directly into github actions etc then, and  can actually be used (if we take container pushing out of generate) to validate configuration, i.e. if `kustomize build .` works on the output manifests

**Comment by prom3theu5** [comment]
I've just added the groundwork for this in https://github.com/prom3theu5/aspirational-manifests/pull/42

**Comment by prom3theu5** [comment]
Base is done for this, and its applied in `init` with state populated pre execution of commands and actions.
Next up is the easy part, roll it out to other actions, and add the shared NonInteractive Option to each command, and command options instance for below. The State extension handler will apply it to the current state instance before execution of a command then, and each of the actions can interrogate `CurrentState.NonInteractive` 

- [ ] Implement in Apply
- [ ] Implement in Destroy
- [ ] Implement in Generate

**Comment by prom3theu5** [comment]
This is now complete - all commands have NonInteractive
I also added a flag on generate '--skip-build' that skips the build and push of containers 😄
