### ISSUE TITLE
If publish fails, aspirate still gives success status

### ISSUE THREAD

**Issue by timheuer** [prom3theu5/aspirational-manifests#41]
### 🔥 Bug Description
If a publish to a registry fails, the status still indicates succes

### 🔍 Steps to Reproduce the Bug
1. Set a registry that is invalit
2. `aspirate generate`
OBSERVE: publish failed but the aspirate status gives me ✔️  vibes
```
/usr/local/share/dotnet/sdk/8.0.100/Containers/build/Microsoft.NET.Build.Containers.targets(202,5): error :    at
Microsoft.NET.Build.Containers.Tasks.CreateNewImage.PushToRemoteRegistryAsync(BuiltImage builtImage, SourceImageReference
sourceImageReference, DestinationImageReference destinationImageReference, CancellationToken cancellationToken) in
/_/src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs:line 199
[/Users/timheuer/Projects/aspire1/aspire1.ApiService/aspire1.ApiService.csproj]
	(✔) Done:  Building and Pushing container for project apiservice
```

### 🧯 Possible Solution
* Observe the error state of previous commands and mirror correct state

**Comment by prom3theu5** [comment]
That's strange!
Is that the current release of dotnet, or a preview?

Mine when I do that raises error 'CONTAINER1013' - whats strange is it says the same line number as the error yours throws on - at that target
For instance - this is me throwing an image at google lol
![image](https://github.com/prom3theu5/aspirational-manifests/assets/1518610/75535922-65e6-473a-99c3-6d92257b0d07)
