### ISSUE TITLE
Error while running 'aspire apply'

### ISSUE THREAD

**Issue by adamtrip** [prom3theu5/aspirational-manifests#60]
Hi there!

Having an error while deploying to my k8s cluster. Tried with the one I created for this and also with the one that comes with docker-desktop. Using a private fallback registry as well.

The app I'm trying to deploy is the starter template that comes with VS Studio,

```
Error from server (BadRequest): error when creating
"C:\\Users\\Adam\\source\\repos\\AspireApp4\\AspireApp4.AppHost\\aspirate-output": Service in version "v1" cannot be handled
as a Service: json: cannot unmarshal array into Go struct field ServiceSpec.spec.selector of type string
Error from server (BadRequest): error when creating
"C:\\Users\\Adam\\source\\repos\\AspireApp4\\AspireApp4.AppHost\\aspirate-output": Service in version "v1" cannot be handled
as a Service: json: cannot unmarshal array into Go struct field ServiceSpec.spec.selector of type string
Failed to deploy manifests in 'C:\Users\Adam\source\repos\AspireApp4\AspireApp4.AppHost\aspirate-output'
```

Might be some config error because I'm not an expert on k8 at all.
Any extra info you might need please ask

Thanks in advance!

**Comment by prom3theu5** [comment]
Hi Adam

Sorry I've been out today - this sounds like a bug has been introduced into the service template in the last lot of work that Introduced dockerfile support.

Give me an hour to get settled at home, and i'll run through some tests and see if I can replicate

**Comment by prom3theu5** [comment]
Sorry about this - Yeah I was right, introduced a regression issue with the implementation of dockerfile support - I've just kicked off the release build which will be on nuget in around 5 mins

Update to preview [v0.1.0-preview-10](https://github.com/prom3theu5/aspirational-manifests/releases/tag/v0.1.0-preview-10) first chance you get - you'll have to run `aspirate generate` again - but you can do that from the same AppHost directory, it'll overwrite the incorrect service manifests 😄

**Comment by prom3theu5** [comment]
Live now :)
