### ISSUE TITLE
Allow override of k8s namespace during deployment/generation

### ISSUE THREAD

**Issue by aabs** [prom3theu5/aspirational-manifests#81]
### 🚀 Feature Description
As a user, I'd like to be able to supply the namespace during deployment or generation, in order to deploy somewhere other than the `default` namespace.

### ✔ Goals
- [ ] create a CLI option for providing a namespace. If not supplied defaults to `default`.

PS. Apolgies if this is already available.  I wasn't able to find it in the CLI help or the docs...

**Comment by prom3theu5** [comment]
Great idea

I'll add support this weekend 😄

**Comment by prom3theu5** [comment]
Handled in release `0.1.20-preview` thats just been pushed.
Can be seen in docs here https://prom3theu5.github.io/aspirational-manifests/generate-command.html

Its `--namespace` or the env var `ASPIRATE_NAMESPACE` when running the `generate` command
