### ISSUE TITLE
QA: Extend Aspirate to generate Radius manifest files.

### ISSUE THREAD

**Issue by flibbertigibbet-uk** [prom3theu5/aspirational-manifests#82]
I have been looking at both Aspirate and the new Radius K8s deployment tooling from Microsoft. There is currently a functional gap between the Aspire and Radius tooling that Aspirate might be able to plug. Has this been considered?

Extending Aspirate to handle Bicep files, an Org level Bicep repository and the declaration of cloud resources outside the scope of a K8s cluster would be a major development, I knowledge.

I am tempted to start work coding up this idea initially in my own medium-term forked repository, however I don't want to expend weeks of effort on something that might at an advanced stage of planning here.

**Comment by prom3theu5** [comment]
That's a good idea

Right now we don't do anything with bicep or terraform etc. it's purely just manifest support. 

Might be more of a fit for AZD, but I can definitely throw some designs together and see how it could fit 😄
