### ISSUE TITLE
Add support for dapr resources

### ISSUE THREAD

**Issue by davidfowl** [prom3theu5/aspirational-manifests#84]
Here's the PR that supports the dapr resources in azd https://github.com/Azure/azure-dev/pull/2992. We should figure out what the right approach is for Kubernetes. 

https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-overview/

cc @philliphoff

**Comment by prom3theu5** [comment]
Right now i'm considering the following: 

- During `generate` we would have a Dapr component processor which would output kustomize manifests to a dapr subfolder.
- Adding another action which can be chained into the apply command, which would prompt for installation of dapr in the cluster utilising the dapr cli, only if the output of `dapr status -k` is an exit code other than 0.
- Handle dapr components (see technical)

Technical:
if a user has said no to dapr deploy - what do we do here... allow to continue and patch the kustomization to remove the dapr components, or exit?
I think we should probably exit - as the app wouldn't run without the dapr components being deployed anyway.

This way during generation we still get the dapr components created as dapr k8s components (the cli adds the CRDs for the resource types)

**Comment by prom3theu5** [comment]
[Added in 0.1.25-preview](https://github.com/prom3theu5/aspirational-manifests/compare/v0.1.24-preview...v0.1.25-preview)
