### ISSUE TITLE
Builder not running

### ISSUE THREAD

**Issue by umerkle** [prom3theu5/aspirational-manifests#94]
### 🔥 Bug Description
I installed Aspire and Aspirate just like shown in your video in the README.md.
Everything worked fine, until i tried to run `aspirate generate`.
After showing the log message 

> Building all project resources, and pushing containers:

it says:

> docker is not running.
> (1): Aspirate will now exit.

But if i try to manually call docker e.g. with `docker info`, docker is running fine.
`docker info` gets:

> Client:
>  Version:    24.0.5
>  Context:    default
>  Debug Mode: false
>  Plugins:
> WARNING: Plugin "/home/xxx/.docker/cli-plugins/docker-buildx" is not valid: failed to fetch metadata: fork/exec /home/xxx/.docker/cli-plugins/docker-buildx: no such file or directory
> WARNING: Plugin "/home/xxx/.docker/cli-plugins/docker-compose" is not valid: failed to fetch metadata: fork/exec /home/xxx/.docker/cli-plugins/docker-compose: no such file or directory
> 
> Server:
>  Containers: 0
>   Running: 0
>   Paused: 0
>   Stopped: 0
>  Images: 9
>  Server Version: 24.0.5
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Using metacopy: false
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: systemd
>  Cgroup Version: 2
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: io.containerd.runc.v2 runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 
>  runc version: 
>  init version: 
>  Security Options:
>   apparmor
>   seccomp
>    Profile: builtin
>   cgroupns
>  Kernel Version: 6.5.0-10010-tuxedo
>  Operating System: TUXEDO OS 2
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 20
>  Total Memory: 62.53GiB
>  Name: uwe-tuxedoinfinitybookprogen7mk1
>  ID: 41041691-4de4-4834-989d-227e014b5c7e
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false

I'm running under Linux. 
`uname -or` gets:

> 6.5.0-10010-tuxedo GNU/Linux

TUXEDO OS is an Ubuntu-based distribution developed in Germany by TUXEDO Computers GmbH

### 🔍 Steps to Reproduce the Bug

- dotnet tool install -g aspirate --prerelease
- dotnet new aspire-starter --use-redis-cache
- cd AspireTests.AppHost/
- aspirate init
- aspirate generate

### 🧯 Possible Solution
* Usefull tips or places to start go here.

**Comment by prom3theu5** [comment]
Thats interesting

Whats the value of `echo $?` after you run `docker info` ?
If those docker-compose warnings changed the exit code from 0 - that would explain it

**Comment by prom3theu5** [comment]
Thanks for checking

I've improved the checking of builders, and commands in general with the latest commit
It will / should at least give you more information on the output if it can't find docker running for some reason

Please test with version `0.1.26-preview` when it hits nuget in a few mins

**Comment by prom3theu5** [comment]
Seems to be the dotnet sdk throwing the error I think, as thats responsible for building and pushing projects.

Can you navigate to the directory `/home/xxx/SCM/_local/AspireTests/AspireTests.ApiService` please and try running:

```bash
dotnet publish AspireTests.ApiService.csproj -p:PublishProfile="DefaultContainer" -p:PublishSingleFile="true" -p:PublishTrimmed="false" --self-contained "true" --os "linux" --arch "x64"
```

Lets see the output of that please

**Comment by umerkle** [comment]
The output is:

> MSBuild-Version 17.8.3+195e7f5a3 für .NET
>   Wiederherzustellende Projekte werden ermittelt...
>   "/home/xxx/SCM/_local/AspireTests/AspireTests.ApiService/AspireTests.ApiService.csproj" wiederhergestellt (in "2,74 sec").
>   "/home/xxx/SCM/_local/AspireTests/AspireTests.ServiceDefaults/AspireTests.ServiceDefaults.csproj" wiederhergestellt (in "2,74 sec").
>   AspireTests.ServiceDefaults -> /home/xxx/SCM/_local/AspireTests/AspireTests.ServiceDefaults/bin/Release/net8.0/AspireTests.ServiceDefaults.dll
>   AspireTests.ApiService -> /home/xxx/SCM/_local/AspireTests/AspireTests.ApiService/bin/Release/net8.0/linux-x64/AspireTests.ApiService.dll
>   AspireTests.ApiService -> /home/xxx/SCM/_local/AspireTests/AspireTests.ApiService/bin/Release/net8.0/linux-x64/publish/
>   Das Image „aspiretests-apiservice“ mit den Tags „latest“ wird auf dem Basisimage „mcr.microsoft.com/dotnet/runtime-deps:8.0“ erstellt.
>   Fehler beim Lesen der Daemonkonfiguration: CONTAINER3002: Fehler beim Abrufen von Docker-Informationen: An error occurred trying to start process '/home/xxx/.rd/bin/docker' with working directory '/home/xxx/SCM/_local/AspireTests/AspireTests.ApiService'. No such file or directory
> /home/xxx/.dotnet/sdk/8.0.100/Containers/build/Microsoft.NET.Build.Containers.targets(202,5): error CONTAINER1012: Die lokale Registrierung ist nicht verfügbar, es wurde jedoch eine Pushübertragung in eine lokale Registrierung angefordert. [/home/xxx/SCM/_local/AspireTests/AspireTests.ApiService/AspireTests.ApiService.csproj]

**Comment by prom3theu5** [comment]
Thanks - thats the same - its the dotnet sdk throwing the error, not aspirate directly
For some reason the dotnet sdk built-in container building is unable to access the local docker registry.

What you could try doing instead is spinning up a local registry manually with

```bash
docker run -d -p 5001:5000 --restart always --name registry registry:2
```
then in your AppHost directory, run `aspirate init`

When it asks if you'd like to use a fall-back container registry, say (Y) and enter: `localhost:5001`

Then try running `aspirate generate` again please 😄  
This will instruct the images to be published to that registry running as a container.

**Comment by umerkle** [comment]
Hoooray! That's it.

Runs like a charm :-)

Thank you very much!

**Comment by prom3theu5** [comment]
Awesome 😄 
You're welcome

Have fun!
